require('core.plugins-config.gruvbox')
require('core.plugins-config.lualine')
require('core.plugins-config.nvim-tree')
require('core.plugins-config.treesitter')
require('core.plugins-config.telescope')
